mode_invariant_whole_body_planner:
  # Defines the desired locomotion state
  desired_state:
    position: {LX: 0., LY: 0., LZ: -0.15, AX: 0., AY: 0., AZ: 0.}
    velocity: {LX: 0., LY: 0., LZ: 0., AX: 0., AY: 0., AZ: 0.}
    acceleration: {LX: 0., LY: 0., LZ: 0., AX: 0., AY: 0., AZ: 0.}
  
  # Defines the constrained dynamical constraint properties
  dynamical_system:
    # Time integration configuration
    time_integration:
      type: fixed
      step_time: 0.0125
      method: EulerBackward
  
  # Defines the cost weights used by the cost functions implemented in the optimizer
  # Defaults values of the weights are 0.
  terminal_cost:
    state_tracking_energy:
      position:
        base: {LX: 1000., LY: 1000., LZ: 1000., AX: 1000., AY: 1000., AZ: 1000.}
        joints: {hfe_joint: 0., kfe_joint: 0.}
      velocity:
        base: {LX: 10., LY: 10., LZ: 10., AX: 10., AY: 10., AZ: 10.}
        joints: {hfe_joint: 10., kfe_joint: 10.}
      acceleration:
        base: {LX: 0.1, LY: 0.1, LZ: 0.1, AX: 0.1, AY: 0.1, AZ: 0.1}  
        joints: {hfe_joint: 0.1, kfe_joint: 0.1}
  integral_cost:
    state_tracking_energy:
      position:
        base: {LX: 1000., LY: 1000., LZ: 1000., AX: 1000., AY: 1000., AZ: 1000.}
        joints: {hfe_joint: 0., kfe_joint: 0.}
      velocity:
        base: {LX: 10., LY: 10., LZ: 10., AX: 10., AY: 10., AZ: 10.}
        joints: {hfe_joint: 10., kfe_joint: 10.}
      acceleration:
        base: {LX: 0.1, LY: 0.1, LZ: 0.1, AX: 0.1, AY: 0.1, AZ: 0.1}  
        joints: {hfe_joint: 0.1, kfe_joint: 0.1}   
    control_energy:
      hfe_joint: 0.001
      kfe_joint: 0.001
  
  # The interpolation time
  # No interpolation rule is applied is the interpolation time is 0
  interpolation_time: 0.005
    
  # The optimization horizon
  horizon: 10
  # The maximum allowed computation time for optimization solver in seconds
  # The default computation time is infinity.
  computation_time: 200