hierarchical_planner:
  # Defining the goal state
  goal: {x: 1.6, y: 0, yaw: 0}
  
  # Defining the robot properties
  robot:
    body_movement_primitives: /home/cmastalli/ros_workspace/src/dwl_planners/config/hyq/body_motor_primitives.yaml
    nominal_stance:
      LF: {x: 0.36, y: 0.32}
      RF: {x: 0.36, y: -0.32}
      LH: {x: -0.36, y: 0.32}
      RH: {x: -0.36, y: -0.32}
    footstep_area: {x: 0.125, y: 0.125} #stance_size
    body_area: {x: 0, y: 0} #TODO
    leg_area: {x: 0, y: 0} #TODO
    
  
  # Defining the body planner
  body_planner:
    type: SearchBasedBody
    # There are several solver such as AnytimeRepairingAStar, AStar and Dijkstrap
    # The default solver is the ARA*
    path_solver: AnytimeRepairingAStar
    ###### TODO: pose_solver:
    # There are several adjacency model such as LatticeBasedBodyAdjacency and GridBasedBodyAdjacency
    # The default adjacency model is LatticeBasedBody without body features
    adjacency:
      name: LatticeBasedBodyAdjacency
      features:
        potential_leg_collision: {enable: true, weight: 500}
        potential_body_orientation: {enable: false, weight: 50}
    # The maximum allowed computation time for path solver in seconds. Note that this time is used only in Anytime algorithms
    # The default computation time is 1 sec.
    path_computation_time: 15
    ###### TODO: pose_computation_time:
    
  contact_planner:
    type: GreedyFootstep
    features:
      support_triangle: {enable: false, weight: 100}
      leg_collision: {enable: true, weight: 5000}
      body_orientation: {enable: false, weight: 5}
    # The contact horizon; the zero value disable a horizon, i.e. it computes all the contact sequence
    horizon: 0
    # The maximum allowed computation time for contact solver in seconds
    # The default computation time is 1 sec.
    computation_time: 0.5
    